# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvatheme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='slide',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
